- hosts: all
  become: yes
  vars:
    docker_packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - docker-ce
      - docker-ce-cli
      - containerd.io
      
  tasks:
    - name: 安裝development group
      yum:
        name: "@Development tools"
        state: present

    - name: 加docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: 安裝docker ce及依賴套件
      yum:
        name: "{{ docker_packages }}"
        state: present
      notify: restart docker

    - name: vagrant進入docker群組
      user:
        name: vagrant
        group: docker
        append: yes

    - include_tasks: common_package.yml

  handlers:
    - name: restart docker
      service: 
        name: docker
        state: restarted
        enabled: yes
    
    - name: restart lxcfs
      service:
        name: lxcfs
        state: restarted
        enabled: yes
